# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.2 on 2023-12-07 09:15

import django.db.models.deletion
from django.db import migrations, models

import django_vault.models.customer_vault


class Migration(migrations.Migration):
    initial = True

    dependencies = [("django_accounts", "0017_remove_address_data_for_company_can_not_be_null_and_more")]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(default="", max_length=128, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ChannelPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("additional_data", models.JSONField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("payu_card", "PayU Card"),
                            ("payu_card_add", "PayU Card Add"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_vault.channel")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CustomerPaymentVault",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "first_transaction_id",
                    models.CharField(
                        default=django_vault.models.customer_vault.generate_first_transaction_id,
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "ext_customer_id",
                    models.CharField(
                        default=django_vault.models.customer_vault.generate_ext_customer_id, max_length=128, unique=True
                    ),
                ),
                (
                    "channel_for_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_channel",
                        to="django_vault.channelpayment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_customer",
                        to="django_accounts.customer",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
